# action.yaml
name: 'Python Interrogate Check'
description: 'Customisable GitHub action to use interrogate to check Python docstring coverage in your repository'
branding:
  icon: 'book-open'
  color: 'blue'
inputs:
  path:
    description: 'File or directory to run interrogate on.'
    required: True
  fail-under:
    description: 'Fail when coverage % is less than a given amount.'
    required: false
    default: '80'
  # exclude:
  #   description: 'Exclude PATHs of files and/or directories.'
  #   required: false
  # ignore-init-method:
  #   description: 'Ignore `__init__` method of classes.'
  #   required: false
  #   default: 'False'
  # ignore-init-module:
  #   description: 'Ignore `__init__.py` modules.'
  #   required: false
  #   default: 'False'
  badge-location:
    description: 'Generate a `shields.io` status badge (an SVG image) in at a given file or directory.'
    required: false
    default: '.'
  ignore-nested-classes:
    description: 'Ignore nested functions and methods.'
    required: false
    default: 'false'
  ignore-private:
    description: 'Ignore private classes, methods, and functions starting with two underscores.'
    required: false
    default: 'false'
  ignore-semiprivate:
    description: 'Ignore semiprivate classes, methods, and functions starting with a single underscore.'
    required: false
    default: 'false'
  ignore-magic:
    description: 'Ignore all magic methods of classes.'
    required: false
    default: 'false'
outputs:
  output:
    description: 'The output of interrogate.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.fail-under }}
    # - ${{ inputs.exclude }}
    # - ${{ inputs.ignore-init-method }}
    # - ${{ inputs.ignore-init-module }}
    - ${{ inputs.badge-location }}
    - ${{ inputs.ignore-nested-classes }}
    - ${{ inputs.ignore-private }}
    - ${{ inputs.ignore-semiprivate }}
    - ${{ inputs.ignore-magic }}
